---
- name: Install prerequisites
  apt:
    pkg:
    - software-properties-common

- name: Add deadsnakes PPA (for newer Python versions)
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install Python
  apt:
    pkg:
    - python3.9
    - python3.9-venv
    - python3.9-dev
    - python3-pip
