---
- hosts: all
  become: true
  vars_files:
    - "group_vars/{{ client }}.yml"
  roles:
    - folder_structure
    - users
    - python
    - postgres
    - nginx
    - gunicorn
    - django
    - certbot
    - pgbouncer
    - docker

- hosts: appserver



- hosts: statsserver
