---
- name: Install Gunicorn on Ubuntu
  hosts: all
  become: yes 

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Gunicorn using pip
      pip:
        name: gunicorn
        state: present
